name = "type-battle-cloudflare-worker"
main = "src/worker.ts"
compatibility_date = "2026-07-04"

[durable_objects]
bindings = [
  { name = "GATEWAY", class_name = "RoomDurableObject" },
  { name = "ROOMS", class_name = "RoomAuthorityDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDurableObject"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["RoomAuthorityDurableObject"]
